### PR TITLE
Unity Package Conversion

### PR DESCRIPTION
**Pull request by michael-nischt**
- Converted to a Unity Package
- Adjusted namespace to reflect style of other Unity packages
- Adjusted menu entry to better fit into the window tab
- Added script and editor assembly definitions (required by Unity 2018.3 for packages)
- Adjusted README (usage part)

### CODE REVIEW

**Comment by romainf-unity** [comment]
Hi!
Thank you for the PR.
I am actually in the process of making the PlayableGraph Visualizer a package already (see [forum thread](https://forum.unity.com/threads/playablegraph-visualizer-package-in-preview.602035/)).

Right now it's in a private repository (because of internal reason), but both repos (this one and the private one) will be kept in synced.

I might take a few of the changes you did though (like the menu entry and the namespace).

**Comment by romainf-unity** [comment]
I pushed the `package` branch into the public repo, so you can take a look: https://github.com/Unity-Technologies/graph-visualizer/tree/package

As soon as the package is stable, `package` will be merged to `master`.

**Comment by michael-nischt** [comment]
Cool, you need to add Assembly Definitions to the ~~Scripts~~ *Client* and *Editor* folders with the one in the later depending on the first. Otherwise, the package won't work with Unity 2018.3+ which requires all scripts in packages to be part of Assembly Definitions.

**Comment by romainf-unity** [comment]
Yup! I've created two folders: `Editor` and `Runtime` (that's the naming convention we defined internally). Each folder have their asmdef, and Editor depends on Runtime.

I've tested from 2018.1 to 2019.1 and it worked fine ;)

**Comment by michael-nischt** [comment]
Perfect, I'll close the PR then! 
Would be great if you can add a namespace also to the Runtime script and fix the menu entry eventually.

**Pull request closed without merging**
